export const upgrades = [
    {
        name: "Paint brush",
        description: "Adds +1 red to your clicks",
        maxRanks: 10,
        price: [100,0,0],
        effect: 1,
        effectModifier: "add" /* add, sub, multiply */,
        type: "click",
    },
    {
        name: "Paint bucket",
        description: "Adds +0.1 red to your clicks for each vertex acquired",
        maxRanks: 5,
        price: [0,10,0],
        effect: 0.1,
        effectModifier: "add",
        type: "vertex.click",
    },
    {
        name: "Vertex extraction",
        description: "Gains +0.1% RPS for each vertex owned",
        maxRanks: 10,
        price: [0,10,0],
        effect: 0.001,
        effectModifier: "add",
        type: "vertex.rps",
    },
    {
        name: "Brighter colors",
        description: "You gain +10% rps",
        price: [100,1,0],
        effect: 1.1,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "Higher saturation",
        description: "You gain +20% rps",
        price: [0,3,0],
        effect: 1.2,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "Redder reds",
        description: "You gain +30% rps",
        price: [0,10,0],
        effect: 1.3,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "Bluer blues",
        description: "You gain +40% rps",
        price: [0,50,0],
        effect: 1.4,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "Greener greens",
        description: "You gain +50% rps",
        price: [0,80,0],
        effect: 1.5,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "CMYK",
        description: "Double your rps",
        price: [0,100,0],
        effect: 2,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "Better color mixing",
        description: "Triples your rps",
        price: [0,150,0],
        effect: 3,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "JPEG artifacts",
        description: "For some reasons gains you +1% rps",
        price: [0,100,0],
        effect: 1.01,
        effectModifier: "multiply",
        type: "rps",
    },
    //add color to upgrade types
    {
        name: "SCART connectors",
        description: "Awards you 1 minute of rps",
        price: [0,1,0],
        effect: 1,
        effectModifier: "time",
        type: "rps",
    },
    {
        name: "RCA connectors",
        description: "Awards you 5 minutes of rps",
        price: [0,4,0],
        effect: 5,
        effectModifier: "time",
        type: "rps",
    },
    {
        name: "VGA connectors",
        description: "Awards you 15 minutes of rps",
        price: [0,75,0],
        effect: 15,
        effectModifier: "time",
        type: "rps",
    },
    {
        name: "DVI connectors",
        description: "Awards you 30 minutes of rps",
        price: [0,200,0],
        effect: 30,
        effectModifier: "time",
        type: "rps",
    },
    {
        name: "HDMI connectors",
        description: "Awards you 45 minutes of rps",
        price: [0,0,2],
        effect: 45,
        effectModifier: "time",
        type: "rps",
    },
    {
        name: "DisplayPort connectors",
        description: "Awards you 1 hour of rps",
        price: [0,0,8],
        effect: 60,
        effectModifier: "time",
        type: "rps",
    },
]