export const upgrades = [
    {
        name: "Paint brush",
        description: "Adds +1 red to your clicks",
        maxRanks: 10,
        price: [100,0,0],
        effect: 1,
        effectModifier: "add" /* add, sub, multiply, time */,
        type: "click",
    },
    {
        name: "Paint bucket",
        description: "Adds +0.1 red to your clicks for each vertex acquired",
        maxRanks: 5,
        price: [0,10,0],
        effect: 0.1,
        effectModifier: "add",
        type: "vertex.click",
    },
    {
        name: "Vertex extraction",
        description: "Gains +0.1% RPS for each vertex owned",
        maxRanks: 10,
        price: [0,10,0],
        effect: 0.001,
        effectModifier: "add",
        type: "vertex.rps",
    },
    {
        name: "Brighter colors",
        description: "You gain +10% rps",
        price: [100,1,0],
        effect: 1.1,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "Higher saturation",
        description: "You gain +10% rps",
        price: [0,3,0],
        effect: 1.1,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "Redder reds",
        description: "You gain +15% rps",
        price: [0,8,0],
        effect: 1.15,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "Bluer blues",
        description: "You gain +15% rps",
        price: [0,25,0],
        effect: 1.15,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "Greener greens",
        description: "You gain +15% rps",
        price: [0,75,0],
        effect: 1.15,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "CMYK",
        description: "You gain +25% rps",
        price: [0,100,0],
        effect: 1.25,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "Better color mixing",
        description: "You gain +25% rps",
        price: [0,150,0],
        effect: 1.25,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "JPEG artifacts",
        description: "For some reasons gains you +1% rps",
        price: [0,100,0],
        effect: 1.01,
        effectModifier: "multiply",
        type: "rps",
    },
    //add color to upgrade types
    {
        name: "SCART connectors",
        description: "Multiples click value by 2%",
        price: [0,1,0],
        effect: 1.02,
        effectModifier: "multiply",
        type: "click",
    },
    {
        name: "RCA connectors",
        description: "Multiples click value by 4%",
        price: [0,4,0],
        effect: 1.04,
        effectModifier: "multiply",
        type: "click",
    },
    {
        name: "VGA connectors",
        description: "Multiples click value by 6%",
        price: [0,75,0],
        effect: 1.06,
        effectModifier: "multiply",
        type: "click",
    },
    {
        name: "DVI connectors",
        description: "Multiples click value by 8%",
        price: [0,200,0],
        effect: 1.08,
        effectModifier: "multiply",
        type: "click",
    },
    {
        name: "HDMI connectors",
        description: "Multiples click value by 10%",
        price: [0,0,2],
        effect: 1.1,
        effectModifier: "multiply",
        type: "click",
    },
    {
        name: "DisplayPort connectors",
        description: "Multiples click value by 10%",
        price: [0,0,8],
        effect: 1.1,
        effectModifier: "multiply",
        type: "click",
    },
]