export const upgrades = [
    {
        name: "Paint brush",
        description: "Adds +1 red to your clicks",
        maxRanks: 10,
        price: [100,0,0],
        effect: 1,
        effectModifier: "add" /* add, sub, multiply */,
        type: "click",
    },
    //Add vertex-rps and vertex-click, possibly others
    {
        name: "Paint bucket",
        description: "Adds +1 red to your clicks for each vertex acquired",
        maxRanks: 5,
        price: [0,10,0],
        effect: 1,
        effectModifier: "add",
        type: "click",
    },
    {
        name: "Vertex extraction",
        description: "Gains +0.1% RPS for each vertex owned",
        maxRanks: 10,
        price: [0,10,0],
        effect: 0.001,
        effectModifier: "add",
        type: "vertex",
    },
    {
        name: "Brighter colors",
        description: "You gain +10% rps",
        price: [100,1,0],
        effect: 1.1,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "Higher saturation",
        description: "You gain +20% rps",
        price: [0,3,0],
        effect: 1.2,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "Redder reds",
        description: "You gain +30% rps",
        price: [0,10,0],
        effect: 1.3,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "Bluer blues",
        description: "You gain +40% rps",
        price: [0,50,0],
        effect: 1.4,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "Greener greens",
        description: "You gain +50% rps",
        price: [0,80,0],
        effect: 1.5,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "CMYK",
        description: "Double your rps",
        price: [0,100,0],
        effect: 2,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "Better color mixing",
        description: "Triples your rps",
        price: [0,150,0],
        effect: 3,
        effectModifier: "multiply",
        type: "rps",
    },
    {
        name: "JPEG artifacts",
        description: "For some reasons gains you +1% rps",
        price: [0,100,0],
        effect: 1.01,
        effectModifier: "multiply",
        type: "rps",
    },
    //add color to upgrade types
    {
        name: "YPbPr",
        description: "Awards you 1 Blue",
        price: [0,100,0],
        effect: 1,
        effectModifier: "add",
        type: "color",
    },
]